#undef TAPPING_TERM
#define TAPPING_TERM 149

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 300000

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 13

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 8

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 120

#undef MOUSEKEY_WHEEL_INTERVAL
#define MOUSEKEY_WHEEL_INTERVAL 70

#define HOLD_ON_OTHER_KEY_PRESS
#define SERIAL_NUMBER "oqJ0w/Eempyv"
#define LAYER_STATE_16BIT

#define RGB_MATRIX_STARTUP_SPD 60

